//Generated by ErrorPro
dtmc
//Element consts
const int Sensor=0;
const int Transmitter=1;
const int Channel_1=2;
const int Channel_2=3;
const int Channel_3=4;
const int Processor=5;
const int Receiver=6;
//Data values consts
const int ok=0;
const int error=1;
//Control flow commands
module control_flow
	cf:[0..7] init Sensor;
	[Sensor] cf=Sensor -> 1:(cf'=Transmitter);	// <--
	[Transmitter] cf=Transmitter -> 1:(cf'=Channel_1);	// <-- 
	[Transmitter] cf=Transmitter -> 1:(cf'=Channel_2);	// <-- 
	[Transmitter] cf=Transmitter -> 1:(cf'=Channel_3);	// <--
	[Channel_1] cf=Channel_1 -> 1:(cf'=Receiver);	// <--
	[Channel_2] cf=Channel_2 -> 1:(cf'=Receiver);	// <--
	[Channel_3] cf=Channel_3 -> 1:(cf'=Receiver);	// <--
	[Processor] cf=Processor -> 1:(cf'=Sensor);	// <--
	[Receiver] (cf=Receiver) & (CONSENSUS=ok) -> 1:(cf'=Processor);	// <-- 
	[Receiver] (cf=Receiver) & (CONSENSUS=error) -> 1:(cf'=Receiver);	// <--
endmodule
//Error propagation commands
module error_propagation
	SAMPLE : [0 .. 1] init ok;
	REPLICA_1 : [0 .. 1] init ok;
	REPLICA_2 : [0 .. 1] init ok;
	REPLICA_3 : [0 .. 1] init ok;
	RECEIVED_1 : [0 .. 1] init ok;
	RECEIVED_2 : [0 .. 1] init ok;
	RECEIVED_3 : [0 .. 1] init ok;
	RECEIVED_SAMPLE : [0 .. 1] init ok;
	CONSENSUS : [0 .. 1] init ok;
	//Element Sensor, df outputs ['SAMPLE']
	[Sensor] (true) -> 1:(SAMPLE'=ok);	// <-- 
	//Element Transmitter, df inputs ['SAMPLE'], df outputs ['REPLICA_1', 'REPLICA_2', 'REPLICA_3']
	[Transmitter] (SAMPLE=ok) -> (REPLICA_1'=ok) & (REPLICA_2'=ok) & (REPLICA_3'=ok);	// <-- 
	[Transmitter] (SAMPLE!=ok) -> (REPLICA_1'=error) & (REPLICA_2'=error) & (REPLICA_3'=error);	// <-- 
	//Element Channel_1, df inputs ['REPLICA_1'], df outputs ['RECEIVED_1']
	[Channel_1] (REPLICA_1=ok) -> (RECEIVED_1'=ok);	// <-- 
	[Channel_1] (REPLICA_1!=ok) -> (RECEIVED_1'=error);	// <-- 
	//Element Channel_2, df inputs ['REPLICA_2'], df outputs ['RECEIVED_2']
	[Channel_2] (REPLICA_2=ok) -> (RECEIVED_2'=ok);	// <-- 
	[Channel_2] (REPLICA_2!=ok) -> (RECEIVED_2'=error);	// <-- 
	//Element Channel_3, df inputs ['REPLICA_3'], df outputs ['RECEIVED_3']
	[Channel_3] (REPLICA_3=ok) -> 0.99999:(RECEIVED_3'=ok) + (1-0.99999):(RECEIVED_3'=error);	// <-- 
	[Channel_3] (REPLICA_3!=ok) -> 0.99:(RECEIVED_3'=error) + (1-0.99):(RECEIVED_3'=ok);	// <-- 
	//Element Receiver, df inputs ['RECEIVED_1', 'RECEIVED_2', 'RECEIVED_3', 'CONSENSUS'], df outputs ['RECEIVED_SAMPLE', 'CONSENSUS']
	[Receiver] (RECEIVED_1=ok) & (RECEIVED_2=ok) & (RECEIVED_3=ok) -> (RECEIVED_SAMPLE'=ok) & (CONSENSUS'=ok);	// <-- 
	[Receiver] (RECEIVED_1!=ok) | (RECEIVED_2!=ok) | (RECEIVED_3!=ok) -> (RECEIVED_SAMPLE'=error) & (CONSENSUS'=error);	// <-- 
endmodule
//Failure formulas
formula TransmissionFault = SAMPLE!=RECEIVED_SAMPLE;
